// Copyright 1997 Association for Universities for Research in Astronomy, Inc.,
// Observatory Control System, Gemini Telescopes Project.
// See the file COPYRIGHT for complete details.
//
// $Id$
//
package gemini.sp ;

import java.util.Enumeration ;

/**
 * The Phase 1 Proposal program item. This item contains attributes for the
 * fields of a phase 1 proposal definition (and any observations or other items
 * specified during the phase 1 document preparation).
 */
public class SpPhase1 extends SpRootItem
{

	/**
     * Default constructor.
     */
	protected SpPhase1()
	{
		super( SpType.PHASE_1 ) ;
	}

	/**
     * Create a Science Program from the contained Observations and other
     * program items that were generated by Phase 1 preparation.
     */
	public SpProg createProgram()
	{
		// Make a new program and give it the same title as the phase 1 program.
		SpProg spProg = ( SpProg )SpFactory.createShallow( SpType.SCIENCE_PROGRAM ) ;
		String title = getTitleAttr() ;
		if( title != null )
			spProg.setTitleAttr( title ) ;

		// Copy all of the child SpItems to the new program.
		Enumeration<SpItem> e = children() ;
		SpItem afterChild = null ;
		while( e.hasMoreElements() )
		{
			SpItem child = e.nextElement() ;
			SpItem copy = child.deepCopy() ;

			spProg.doInsert( copy , afterChild ) ;
			afterChild = copy ;
		}

		// Set the Phase1 reference in the new program
		spProg.setPhase1Item( this ) ;

		return spProg ;
	}
}
