#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

from datetime import datetime
import os
import re

stamp = datetime.now().strftime('%Y%m%d%H%M%S')


def add_timestamp(arg, dirname, fnames):
    for file in fnames:
        pathname = os.path.join(dirname, file)
        (root, ext) = os.path.splitext(file)

        if ext == '.jar':
            os.rename(pathname,
                      os.path.join(dirname,
                                   '{0}_{1}{2}'.format(root, stamp, ext)))

        elif ext == '.jnlp':
            with open(pathname, 'r') as f:
                xml = f.readlines()

            with open(pathname, 'w') as f:
                for line in xml:
                    f.write(re.sub('\.jar"', '_{0}.jar"'.format(stamp), line))


if __name__ == '__main__':
    os.path.walk('.', add_timestamp, None)
