#!/bin/csh -f

# Simple startup script for the UKIRT-OT. Just runs the actual
# OT script with the correct options of "ukirt"


# Find out where we are
# Assumes people dont copy me
set mydir=`dirname $0` 

# Now run the ot
${mydir}/ot ukirt $*
